-- Scenario inventory for the 0.0.6 validation release.
-- These rows declare required evidence, not results. A runtime invariant PASS
-- does not mark a whole scenario passed or establish external game accuracy.
-- docs/VALIDATION_MATRIX.md shares the same stable IDs. No engine calls here.
BankValidationCatalog = {
    schemaVersion = 1,
    modVersion = "0.0.6",
    defaultStatus = "NOT_EXERCISED",
    checks = {
        {id = "PKG-001", group = "PKG", evidence = "structural",
            description = "Release identity and root archive layout",
            oracle = "ZIP root contains modDesc.xml; manifest, bootstrap and diagnostics agree on 0.0.6.",
            procedure = "Run build/validator and inspect ZIP names and version fields.",
            logEvidence = "Build output, ZIP list, startup version.",
            relatedTests = "tools/build.py, tools/validate.py"},
        {id = "PKG-002", group = "PKG", evidence = "structural",
            description = "Every declared source and GUI resource exists with exact case",
            oracle = "Manifest load order resolves every global dependency; no absent resource or callback.",
            procedure = "Validate sourceFiles, GUI/profile/icon/localization references.",
            logEvidence = "Validator output, native load errors.",
            relatedTests = "tools/build.py, tools/validate.py"},
        {id = "PKG-003", group = "PKG", evidence = "structural",
            description = "XML, localization and icon integrity",
            oracle = "XML parses; every lb_* string resolves; icon is valid 512px DXT5 with mipmaps.",
            procedure = "Run local validation; inspect native mod selection icon/title.",
            logEvidence = "Validator output and selection screenshot.",
            relatedTests = "tools/build.py, tools/validate.py"},
        {id = "PKG-004", group = "PKG", evidence = "structural",
            description = "Deterministic packaging and isolated runtime payload",
            oracle = "Repeated unchanged builds have identical SHA256; archive includes needed runtime files and no tests, caches or dev tools.",
            procedure = "Build twice and compare hashes/list; install only ZIP.",
            logEvidence = "Build hashes and ZIP inventory.",
            relatedTests = "tools/build.py, tools/validate.py"},
        {id = "PKG-005", group = "PKG", evidence = "manual",
            description = "Clean install without dependencies or stale duplicate copies",
            oracle = "Single enabled Lizard Bank entry loads using only packaged resources.",
            procedure = "Install into active mods folder, enable on disposable save, record other mods.",
            logEvidence = "Full startup log and selected version.",
            relatedTests = "tools/build.py, tools/validate.py"},
        {id = "PKG-006", group = "PKG", evidence = "structural",
            description = "Native parser and GIANTS TestRunner",
            oracle = "Lua 5.1 parse, resource checks and available TestRunner pass; unavailable TestRunner stays pending.",
            procedure = "Run documented local commands and TestRunner if available.",
            logEvidence = "Exact commands, versions and outputs.",
            relatedTests = "tools/build.py, tools/validate.py"},
        {id = "LIFE-001", group = "LIFE", evidence = "fixture",
            description = "Initialization while mission and mode are unavailable",
            oracle = "No farm scan, GUI or observer attaches before ready single-player mission.",
            procedure = "Exercise bootstrap readiness stubs; watch first-ready trace in game.",
            logEvidence = "Startup readiness and initialization events.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-002", group = "LIFE", evidence = "manual",
            description = "Initialize exactly once and capture early load anchor",
            oracle = "One observer/screen per mission; clean saved anchor resumes before game time advances.",
            procedure = "Load a saved ledger; compare startup/resume trace and first checkpoint.",
            logEvidence = "Readiness, hook installation and resume records.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-003", group = "LIFE", evidence = "manual",
            description = "Mission with active farm other than ID 1",
            oracle = "All sections and history use the resolved active farm, never a fixed ID.",
            procedure = "Use a naturally available non-1 farm/save; otherwise fixture only.",
            logEvidence = "Farm ID/source in every checkpoint.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-004", group = "LIFE", evidence = "manual",
            description = "Normal unload cleans owned resources",
            oracle = "Inputs, GUI/focus, commands, hooks and cached mission references release; native controls remain usable.",
            procedure = "Exit to menu with bank open and closed, then load another save.",
            logEvidence = "Teardown and next initialization trace.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-005", group = "LIFE", evidence = "manual",
            description = "Second save in same process",
            oracle = "Only second save assets/ledger appear; no duplicate actions, transaction events or callbacks.",
            procedure = "Load new and established saves sequentially without restarting FS25.",
            logEvidence = "Checkpoint mission/session IDs, event counts.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-006", group = "LIFE", evidence = "manual",
            description = "Remappable action rebuilds without duplicates",
            oracle = "One press opens once after binding changes; other native bindings still work.",
            procedure = "Rebind Open Lizard Bank, apply twice, test old/new binding.",
            logEvidence = "Input registration/removal and open events.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-007", group = "LIFE", evidence = "fixture",
            description = "Single-player restriction and dedicated-server guard",
            oracle = "MP/dedicated execution stays inactive and graceful; manifest declares single-player.",
            procedure = "Inspect manifest and run forced-mode stubs; real MP only if naturally reproducible.",
            logEvidence = "Mode/disabled reason, fixture output.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-008", group = "LIFE", evidence = "fixture",
            description = "GUI initialization failure and focus restoration",
            oracle = "Prior GUI focus is restored; no repeated frame retries, leaked controllers or stale report.",
            procedure = "Fixture missing/load-failing GUI paths.",
            logEvidence = "Initialization error and cleanup records.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-009", group = "LIFE", evidence = "fixture",
            description = "Coexistence with later input/load wrappers",
            oracle = "Native behavior and later mod wrappers survive unload; detached observer cannot resurrect.",
            procedure = "Exercise cooperative wrapper fixtures; repeat with actual installed mods when present.",
            logEvidence = "Wrapper ownership/removal and fixture output.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-010", group = "LIFE", evidence = "fixture",
            description = "Replacement or unavailable farm object",
            oracle = "Old farm hooks release; replacement resolves dynamically; unavailable farm clears stale report.",
            procedure = "Fixture same-ID replacement, different ID and missing farm transitions.",
            logEvidence = "Farm-change, hook and gap events.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-011", group = "LIFE", evidence = "manual",
            description = "Public openReport and console opener",
            oracle = "Open action, lbOpen and openReport share one screen and capture contract.",
            procedure = "Use binding and lbOpen; exercise direct entry in local stub.",
            logEvidence = "Open origin/capture sequence.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "LIFE-012", group = "LIFE", evidence = "manual",
            description = "Observer and diagnostics preserve game behavior",
            oracle = "Bank actions do not change cash, debt, ownership, calendar or native transaction count.",
            procedure = "Compare quiescent before/after repeated open/Refresh/Policy with time paused where possible.",
            logEvidence = "Before/after snapshots and native Finance readings.",
            relatedTests = "tests/test_bootstrap.lua, tests/test_history_runtime.lua"},
        {id = "GUI-001", group = "GUI", evidence = "manual",
            description = "Mouse navigation and Back/Close",
            oracle = "Open, Refresh, Policy, pages and Close respond; cursor and player controls restore.",
            procedure = "Use every button, close and resume movement/driving.",
            logEvidence = "Open/close/click trace and visual observation.",
            relatedTests = "tests/test_report.lua"},
        {id = "GUI-002", group = "GUI", evidence = "manual",
            description = "Keyboard navigation and remapped open key",
            oracle = "Focus order reaches all controls; native Back closes; no stuck controls.",
            procedure = "Navigate without mouse; test Right Ctrl+B and chosen remap.",
            logEvidence = "Input trace plus manual focus result.",
            relatedTests = "tests/test_report.lua"},
        {id = "GUI-003", group = "GUI", evidence = "manual",
            description = "Controller navigation and action glyphs",
            oracle = "Native focus, glyphs, page/Refresh/Policy and Back work on an actual controller.",
            procedure = "Use controller through first/last page and close.",
            logEvidence = "Manual controller/device evidence.",
            relatedTests = "tests/test_report.lua"},
        {id = "GUI-004", group = "GUI", evidence = "manual",
            description = "Page boundaries and large report completeness",
            oracle = "Every asset/issue remains reachable; first/last page controls stay focusable; no clipped lines.",
            procedure = "Inspect largest available save and local long-report fixture.",
            logEvidence = "Page counts, full checkpoint and screenshots.",
            relatedTests = "tests/test_report.lua"},
        {id = "GUI-005", group = "GUI", evidence = "runtime",
            description = "Capture triggers and stale-failure replacement",
            oracle = "Open/Refresh/Policy capture once; page navigation does not scan; failed capture replaces old data.",
            procedure = "Compare capture sequence across actions; fixture a capture failure.",
            logEvidence = "Capture reasons/counts and report status.",
            relatedTests = "tests/test_report.lua"},
        {id = "GUI-006", group = "GUI", evidence = "manual",
            description = "Native currency, area, volume and custom units",
            oracle = "Displayed formatting matches game settings; custom units are not relabeled liters.",
            procedure = "Change normal unit/currency settings if available and compare same values.",
            logEvidence = "Raw snapshot values/unit labels and screenshots.",
            relatedTests = "tests/test_report.lua"},
        {id = "GUI-007", group = "GUI", evidence = "fixture",
            description = "English localization and fallback safety",
            oracle = "Mod-scoped text resolves; missing/malformed translations fall back legibly without crashes.",
            procedure = "Run localization fixtures; inspect GUI under installed game language.",
            logEvidence = "Localization fixture output, GUI text.",
            relatedTests = "tests/test_report.lua"},
        {id = "GUI-008", group = "GUI", evidence = "fixture",
            description = "Long names, mixed IDs and Unicode",
            oracle = "Names wrap within page budget; sorting is deterministic; no source objects leak.",
            procedure = "Run long/Unicode/mixed-ID report fixtures; inspect naturally long names.",
            logEvidence = "Rendered page strings and screenshots where available.",
            relatedTests = "tests/test_report.lua"},
        {id = "GUI-009", group = "GUI", evidence = "manual",
            description = "Zero, unavailable, partial and excluded wording",
            oracle = "Verified empty/zero differs visibly from unknown; omitted items and limits are stated.",
            procedure = "Compare empty new save, populated save and any unsupported source.",
            logEvidence = "Status fields, issues and displayed labels.",
            relatedTests = "tests/test_report.lua"},
        {id = "GUI-010", group = "GUI", evidence = "manual",
            description = "Policy button cycles using native controls",
            oracle = "Standard to Strict to Lenient to Standard; only model policy changes; absent evidence never creates score.",
            procedure = "Cycle with mouse, keyboard and controller; compare source figures.",
            logEvidence = "Mode changes, assessment reasons and unchanged source data.",
            relatedTests = "tests/test_report.lua"},
        {id = "GUI-011", group = "GUI", evidence = "fixture",
            description = "Report release on close and reload",
            oracle = "Screen drops pages/snapshot on close; new mission does not show old report.",
            procedure = "Run screen lifecycle fixture; reopen after save switch.",
            logEvidence = "Screen lifecycle/capture events.",
            relatedTests = "tests/test_report.lua"},
        {id = "SNAP-001", group = "SNAP", evidence = "manual",
            description = "Cash getter, fallback and native UI reconciliation",
            oracle = "Accepted finite cash equals Finance within native display precision; chosen source is named.",
            procedure = "Read native Finance and compare lbValidate; optionally lbExpect cash value.",
            logEvidence = "Cash read/decision trace, expectation provenance.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "SNAP-002", group = "SNAP", evidence = "manual",
            description = "Debt getter, fallback and native UI reconciliation",
            oracle = "Accepted finite nonnegative native loan equals Finance; external borrowing is not inferred.",
            procedure = "Compare Finance before/after borrow and repay; lbExpect debt value.",
            logEvidence = "Debt read/decision trace and native loan deltas.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "SNAP-003", group = "SNAP", evidence = "fixture",
            description = "Zero and negative cash versus unavailable debt",
            oracle = "Zero cash/debt and negative cash stay valid; missing, negative debt and nonfinite data stay unknown.",
            procedure = "Run finite/zero/fallback fixtures; natural zero cases if available.",
            logEvidence = "Value/status/source fields.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "SNAP-004", group = "SNAP", evidence = "fixture",
            description = "Getter and raw-field disagreement",
            oracle = "Source precedence stays explicit and diagnostics flag mismatch; no silent averaging.",
            procedure = "Inject conflicting getter/field values in local fixtures.",
            logEvidence = "Getter-field checks and selected source.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "SNAP-005", group = "SNAP", evidence = "fixture",
            description = "Dynamic identity and invalid/spectator identities",
            oracle = "Unresolved farm cannot attribute assets/history; name is optional; no fake farm 1.",
            procedure = "Fixture missing manager, invalid/spectator IDs and fallback route.",
            logEvidence = "Farm source, capabilities and FARM_UNAVAILABLE.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "SNAP-006", group = "SNAP", evidence = "runtime",
            description = "Dated detached snapshot and version metadata",
            oracle = "Farm, raw game date, game/mod/model/schema versions and source metadata accompany plain copied values.",
            procedure = "Capture then mutate test source objects; inspect live checkpoint metadata.",
            logEvidence = "Checkpoint headers, schema and source fields.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "SNAP-007", group = "SNAP", evidence = "fixture",
            description = "Calendar source fallback and absent date",
            oracle = "Monotonic day wins; fallback remains labeled; missing date stays unknown rather than invented Gregorian date.",
            procedure = "Run calendar precedence/absence fixtures.",
            logEvidence = "capturedAt and calendar capability fields.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "SNAP-008", group = "SNAP", evidence = "fixture",
            description = "Failure isolation at accessor, record and section",
            oracle = "One failed source leaves healthy neighbors and explicit issue; stale successful values are not reused.",
            procedure = "Run throwing/malformed records and whole-section fixtures.",
            logEvidence = "Collector failure boundaries, partial statuses.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "SNAP-009", group = "SNAP", evidence = "runtime",
            description = "Aggregate arithmetic and overflow",
            oracle = "Partial sums equal known eligible values; no NaN/infinity or unknown-to-zero conversion.",
            procedure = "Compare logged item sums and subtotal checks; run overflow fixtures.",
            logEvidence = "Arithmetic invariant results and values.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "SNAP-010", group = "SNAP", evidence = "manual",
            description = "Coverage and valuation scope",
            oracle = "Land/equipment/buildings subtotal remains partial; cash, inventory and animal quotes are not double-counted.",
            procedure = "Compare report subtotal to supported item values and disclosures.",
            logEvidence = "Subtotal ingredients and coverage issues.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "SNAP-011", group = "SNAP", evidence = "fixture",
            description = "Capture repeatability and no economic writes",
            oracle = "Identical inputs give equivalent detached data; collector calls no mutation APIs.",
            procedure = "Run immutable-source fixtures and side-effect sentinels.",
            logEvidence = "Fixture output and repeated checkpoint differences.",
            relatedTests = "tests/test_data.lua, tests/test_report.lua"},
        {id = "LAND-001", group = "LAND", evidence = "manual",
            description = "Strict parcel ownership versus access permission",
            oracle = "Only actual active-farm owners count; contractor/access-only land is excluded.",
            procedure = "Compare map ownership, accessed contract parcel and report.",
            logEvidence = "Parcel owner decisions, IDs and native map evidence.",
            relatedTests = "tests/test_data.lua"},
        {id = "LAND-002", group = "LAND", evidence = "manual",
            description = "Parcel identifiers, whole area and configured prices",
            oracle = "IDs match parcels; area is whole parcel hectares; value is configured current price with source label.",
            procedure = "Inspect known parcels in map/native data and bank; do not equate field area with parcel area.",
            logEvidence = "Land item values, source fields and screenshots.",
            relatedTests = "tests/test_data.lua"},
        {id = "LAND-003", group = "LAND", evidence = "manual",
            description = "Buy/sell land refresh and capital movement",
            oracle = "Owned list/count updates after transaction; actual cash delta is capital; no stale parcel.",
            procedure = "Buy then sell affordable parcel on disposable save, refresh after each.",
            logEvidence = "Ownership decisions, transaction and snapshots.",
            relatedTests = "tests/test_data.lua"},
        {id = "LAND-004", group = "LAND", evidence = "fixture",
            description = "Duplicate aliases and mixed IDs",
            oracle = "Same parcel ID counts once; distinct parcels remain separate and deterministically ordered.",
            procedure = "Run duplicate/mixed-key registry fixtures.",
            logEvidence = "Dedup checks and item counts.",
            relatedTests = "tests/test_data.lua"},
        {id = "LAND-005", group = "LAND", evidence = "fixture",
            description = "No land versus unavailable enumeration",
            oracle = "Verified empty list yields zero; missing manager/list/owner API yields unavailable.",
            procedure = "Run empty/missing registry fixtures.",
            logEvidence = "Capabilities, status and total fields.",
            relatedTests = "tests/test_data.lua"},
        {id = "LAND-006", group = "LAND", evidence = "fixture",
            description = "Unvalued/unknown-owner/malformed parcel",
            oracle = "Unknown owner omitted explicitly; owned unpriced/unmeasured parcel listed without invented values; healthy parcels survive.",
            procedure = "Run bad ownership, price, area and record fixtures.",
            logEvidence = "Issues, unknown counters and item statuses.",
            relatedTests = "tests/test_data.lua"},
        {id = "LAND-007", group = "LAND", evidence = "fixture",
            description = "Land subtotal numeric limits",
            oracle = "Finite known item sums are retained; overflowing totals are unavailable.",
            procedure = "Run extreme/negative/nonfinite area-price fixtures.",
            logEvidence = "LAND_TOTAL_OVERFLOW and absent invalid total.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-001", group = "VEH", evidence = "manual",
            description = "Owned fleet and attached implements count once",
            oracle = "Every owned registered machine/implement appears once, attached or detached.",
            procedure = "Compare garage list and attach/detach one implement before Refresh.",
            logEvidence = "Equipment identities, dedup decisions and counts.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-002", group = "VEH", evidence = "manual",
            description = "Leased machines and return",
            oracle = "Leased rows are labeled and excluded from owned value; returning removes them.",
            procedure = "Lease inexpensive implement, refresh, return, refresh.",
            logEvidence = "State decisions, leased count and value subtotal.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-003", group = "VEH", evidence = "manual",
            description = "Mission borrowed equipment",
            oracle = "Contract/borrowed equipment stays separate and never inflates owned collateral.",
            procedure = "Accept suitable equipment-borrowing contract on disposable save; inspect/report then return.",
            logEvidence = "Borrowed state, contract screen and subtotal.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-004", group = "VEH", evidence = "fixture",
            description = "Other farm and unknown ownership",
            oracle = "Other known owners excluded; unknown owner omitted with issue; access is irrelevant.",
            procedure = "Run ownership fixtures; compare naturally shared/modded assets if present.",
            logEvidence = "Owner checks and omission issues.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-005", group = "VEH", evidence = "manual",
            description = "Native sale quote and contents warning",
            oracle = "Quote uses native getSellPrice once; warn contents may be included; do not add stock money.",
            procedure = "Compare garage/workshop sale quote for empty and loaded trailer without assuming sale-channel fees equal.",
            logEvidence = "Read source, quote value, contents flag and quote screenshot.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-006", group = "VEH", evidence = "manual",
            description = "Buy/sell and transaction amount versus quote",
            oracle = "Purchase/sale updates fleet; recorded capital movement equals actual cash delta even if quote/channel differs.",
            procedure = "Buy affordable item, compare quote, sell and refresh.",
            logEvidence = "Transaction delta, quote and asset removal.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-007", group = "VEH", evidence = "manual",
            description = "Pallet, big bag, train and ridden-horse exclusions",
            oracle = "These objects do not become ordinary equipment collateral; goods/riding exclusions remain visible.",
            procedure = "Inspect existing pallet/big bag/train and ridden horse when available.",
            logEvidence = "Equipment exclusion decisions and inventory/animal coverage.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-008", group = "VEH", evidence = "fixture",
            description = "Missing enumeration/state constants and unknown property",
            oracle = "Fallback registry disclosed; absent enum never assumes numeric values; unknown state listed unvalued.",
            procedure = "Run fallback/missing-enum fixtures.",
            logEvidence = "Registry source, capabilities and unknown-state issue.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-009", group = "VEH", evidence = "fixture",
            description = "Quote failure, zero, all unvalued and empty fleet",
            oracle = "Zero quote valid; failed/negative/nonfinite quote unknown; all unknown not zero; verified empty is zero.",
            procedure = "Run quote and empty-fleet fixtures.",
            logEvidence = "Quote status, unknown counts and subtotal.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-010", group = "VEH", evidence = "fixture",
            description = "Deletion, duplicate ID and missing ID",
            oracle = "Removing object omitted; duplicate identity once; no-ID objects get snapshot-local labels without dropping independent implements.",
            procedure = "Run registry/deletion/ID fixtures.",
            logEvidence = "Dedup/omission events and item list.",
            relatedTests = "tests/test_data.lua"},
        {id = "VEH-011", group = "VEH", evidence = "fixture",
            description = "Overflow and custom accessor isolation",
            oracle = "Bad custom object does not suppress healthy fleet; overflowing subtotal unknown.",
            procedure = "Run malformed/throwing/extreme quote fixtures.",
            logEvidence = "Record errors and subtotal checks.",
            relatedTests = "tests/test_data.lua"},
        {id = "PROP-001", group = "PROP", evidence = "manual",
            description = "Owned registered buildings and production placeables",
            oracle = "Only active-farm owned registered placeables appear once; land access is insufficient.",
            procedure = "Compare construction/owned production screens and bank.",
            logEvidence = "Placeable owner, ID and enumeration trace.",
            relatedTests = "tests/test_property.lua"},
        {id = "PROP-002", group = "PROP", evidence = "manual",
            description = "Engine monetary value and temporary refund distinction",
            oracle = "Display getMonetaryValue basis, not inferred purchase cost or temporary construction refund.",
            procedure = "Place affordable structure, inspect immediate refund/sale UI and bank value, then inspect later.",
            logEvidence = "Value source, quote and native screen evidence.",
            relatedTests = "tests/test_property.lua"},
        {id = "PROP-003", group = "PROP", evidence = "manual",
            description = "Sale veto and unknown eligibility",
            oracle = "canBeSold false/unknown remains advisory; value is never promised net sale proceeds.",
            procedure = "Inspect a native restricted placeable or fixture if unavailable.",
            logEvidence = "Sale eligibility read and caveat.",
            relatedTests = "tests/test_property.lua"},
        {id = "PROP-004", group = "PROP", evidence = "manual",
            description = "Build/sell refresh and removed storage aliases",
            oracle = "Sold placeable disappears; its old stores/counterparts cannot reappear via other registries.",
            procedure = "Build/sell affordable empty storage on disposable save and refresh after completion.",
            logEvidence = "Deletion/alias decisions, property and inventory snapshots.",
            relatedTests = "tests/test_property.lua"},
        {id = "PROP-005", group = "PROP", evidence = "fixture",
            description = "Duplicate objects and registered lookup fallback",
            oracle = "Object/unique-ID aliases count once; documented placableByUniqueId fallback is labeled.",
            procedure = "Run duplicate/fallback fixtures.",
            logEvidence = "Enumeration and duplicate counts.",
            relatedTests = "tests/test_property.lua"},
        {id = "PROP-006", group = "PROP", evidence = "fixture",
            description = "Empty versus unavailable buildings",
            oracle = "Verified no supported buildings gives zero; absent registry/farm gives unavailable.",
            procedure = "Run empty/missing-system fixtures.",
            logEvidence = "Status/count/total fields.",
            relatedTests = "tests/test_property.lua"},
        {id = "PROP-007", group = "PROP", evidence = "fixture",
            description = "Zero and invalid/missing monetary values",
            oracle = "Zero valid; negative, nonfinite or throwing value leaves explicit unvalued row.",
            procedure = "Run quote validation and healthy-neighbor fixtures.",
            logEvidence = "UnknownValueCount and accessor issues.",
            relatedTests = "tests/test_property.lua"},
        {id = "PROP-008", group = "PROP", evidence = "fixture",
            description = "Removing/malformed records and unsafe names",
            oracle = "Deleting and malformed records stay isolated; non-scalar identifiers/names never leak references.",
            procedure = "Run removal/invalid metadata fixtures.",
            logEvidence = "Record issues and detached row output.",
            relatedTests = "tests/test_property.lua"},
        {id = "PROP-009", group = "PROP", evidence = "fixture",
            description = "Property total overflow and detached refresh",
            oracle = "Overflow unavailable; refresh does not retain old object/value references.",
            procedure = "Run overflow/detachment fixtures.",
            logEvidence = "Subtotal checks and fixture output.",
            relatedTests = "tests/test_property.lua"},
        {id = "INV-001", group = "INV", evidence = "manual",
            description = "Silo/extension storage attribution and transfers",
            oracle = "Contents follow verified storage owner; registry aliases/extension do not duplicate quantity.",
            procedure = "Compare silo screen; transfer a known amount to trailer and back, refreshing at each settled state.",
            logEvidence = "Location/fill/unit/owner trace and quantity deltas.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-002", group = "INV", evidence = "manual",
            description = "Owned finalized production inventory",
            oracle = "Dedicated storage follows owned finalized production; unfinished/nonowned sources excluded.",
            procedure = "Compare an existing production inventory and supported purchase/transfer.",
            logEvidence = "Production finalization/owner decisions and quantities.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-003", group = "INV", evidence = "manual",
            description = "Loaded owned and leased containers",
            oracle = "Quantity remains at correct container; leased label shown; cargo title stays unverified even in owned container.",
            procedure = "Load a known quantity in owned or leased trailer; compare native HUD.",
            logEvidence = "Fill-unit reads, container state and cargo warning.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-004", group = "INV", evidence = "manual",
            description = "Pallet/big bag multi-unit stock",
            oracle = "Every supported unit appears once with its actual fill type/unit; goods are not equipment value.",
            procedure = "Compare existing pallet/big bag contents then move/store it.",
            logEvidence = "Unit-level snapshot and exclusion decisions.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-005", group = "INV", evidence = "fixture",
            description = "Native custom unit and missing fill metadata",
            oracle = "Custom unit text retained; known quantity survives absent metadata without inventing liters or crop identity.",
            procedure = "Run custom-unit and absent-manager/type fixtures.",
            logEvidence = "unit/unitText/fillType status and issues.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-006", group = "INV", evidence = "fixture",
            description = "Verified zero versus invalid quantity",
            oracle = "Empty supported compartments count as zero; missing/negative/nonfinite contents stay unknown.",
            procedure = "Run zero/invalid/throwing fill-unit fixtures.",
            logEvidence = "zeroCount, unknownCount and quantityStatus.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-007", group = "INV", evidence = "fixture",
            description = "Missing registry and narrow fallback coverage",
            oracle = "Supported direct adapters survive missing generic registry; absent section never claims full inventory coverage.",
            procedure = "Run missing storage/placeable/vehicle system fixtures.",
            logEvidence = "Coverage by source and registry capability flags.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-008", group = "INV", evidence = "runtime",
            description = "Cargo ownership and monetary nonduplication",
            oracle = "Container ownership never proves cargo title; inventory quantities never add to monetary subtotal.",
            procedure = "Inspect current snapshot/report and compare owned-assets calculation.",
            logEvidence = "cargoOwnership, includedInAssetQuote and subtotal checks.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-009", group = "INV", evidence = "manual",
            description = "Tree-planter mounted pallet proxy",
            oracle = "Mounted sapling pallet counted once; planter proxy excluded; missing actual pallet is a gap.",
            procedure = "Inspect mounted native planter/pallet if available; missing registry remains fixture-only.",
            logEvidence = "Proxy decisions and missing-pallet issue.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-010", group = "INV", evidence = "fixture",
            description = "Storage/vehicle deletion signals and stale aliases",
            oracle = "All supported deletion flags/getter paths prevent stale stock; healthy storage remains.",
            procedure = "Run sold/removing object alias fixtures.",
            logEvidence = "Removal and alias decisions.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-011", group = "INV", evidence = "fixture",
            description = "Unknown owner/property and borrowed container",
            oracle = "Unknown owner/state omitted with explicit gap; mission-container stock is excluded.",
            procedure = "Run owner/state/borrowed fixtures.",
            logEvidence = "Ownership decisions and coverage issues.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-012", group = "INV", evidence = "fixture",
            description = "Quantity source failure isolation and DTO order",
            oracle = "One failed compartment/source leaves neighbors intact; outputs are scalar detached tables in deterministic order.",
            procedure = "Run malformed/accessor/detachment fixtures.",
            logEvidence = "Collector boundary events and fixture output.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "INV-013", group = "INV", evidence = "manual",
            description = "Ground heaps and unsupported crop/timber scope",
            oracle = "Ground heaps, standing crops/timber and unsupported stocks stay explicitly outside quantity/asset coverage.",
            procedure = "Review report on save with such assets; no inferred financial value.",
            logEvidence = "Coverage disclaimer and item inventory.",
            relatedTests = "tests/test_inventory.lua"},
        {id = "BALE-001", group = "BALE", evidence = "manual",
            description = "Native loose bales and raw/wrapped item registry",
            oracle = "Real owned registered bales give current fill type/quantity once; unrelated items ignored.",
            procedure = "Inspect existing bale count/contents; compare a loose bale before/after moving.",
            logEvidence = "Bale class, registry shape and quantity trace.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-002", group = "BALE", evidence = "manual",
            description = "Contract, other-owner and unknown-owner bales",
            oracle = "Contract/other-farm bales excluded; unknown title explicitly unavailable, never presumed owned.",
            procedure = "Inspect naturally available contract bale; fixture missing owner.",
            logEvidence = "Mission/owner exclusion decisions.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-003", group = "BALE", evidence = "manual",
            description = "Loaded or unsellable bale remains current quantity",
            oracle = "Physical bale on loader is still counted once even if cannot currently be sold.",
            procedure = "Load/unload an existing bale, refresh when settled.",
            logEvidence = "Bale registration, handler proxy exclusion and quantity.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-004", group = "BALE", evidence = "manual",
            description = "Fermentation progress and current crop identity",
            oracle = "Actual current fill type and valid progress shown; future silage quantity/value not invented.",
            procedure = "Inspect fermenting and completed bale if available; invalid progress fixture.",
            logEvidence = "Current fill, fermentation status and source.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-005", group = "BALE", evidence = "manual",
            description = "Object storage real counterpart and all aliases",
            oracle = "Stored bale/pallet counts once at storage location across item/vehicle aliases.",
            procedure = "Store then retrieve existing supported object, refreshing after each.",
            logEvidence = "Real-counterpart identity, location and dedup trace.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-006", group = "BALE", evidence = "manual",
            description = "Pure virtual and unknown object-storage records",
            oracle = "Known object count retained, unavailable quantity explicit; UI text never parsed into invented liters.",
            procedure = "Inspect native storage with no readable real counterpart; use fixture if absent.",
            logEvidence = "Stored-record shape, count and unknown quantity issue.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-007", group = "BALE", evidence = "fixture",
            description = "Stored counterpart ownership differs from building",
            oracle = "Foreign/unknown counterpart is not attributed solely because building is owned; loose aliases remain blocked.",
            procedure = "Run counterpart owner and stale-alias fixtures.",
            logEvidence = "Ownership/block decisions.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-008", group = "BALE", evidence = "manual",
            description = "Loader count and straw-blower mirrored fill unit",
            oracle = "Handler count/proxy does not duplicate physical bale; independent fuel/buffer contents remain.",
            procedure = "Inspect available loader/blower, including partial consumption.",
            logEvidence = "Skipped unit reasons and registered bale checks.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-009", group = "BALE", evidence = "manual",
            description = "Round baler chamber transition",
            oracle = "Transient chamber bale quantity omitted with gap; discharge/settle restores supported quantity without duplication.",
            procedure = "Create/discharge native round bale when feasible; otherwise unexercised.",
            logEvidence = "Chamber omission and before/after quantity trace.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-010", group = "BALE", evidence = "manual",
            description = "Square baler and independent material/buffer",
            oracle = "Independent material/buffer remains; round-baler exclusion does not erase square-baler contents.",
            procedure = "Inspect existing square baler/material; fixture if unavailable.",
            logEvidence = "Per-unit proxy decision and quantity source.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-011", group = "BALE", evidence = "fixture",
            description = "Missing class/registry, removed storage and bad getters",
            oracle = "Missing native Bale support differs from verified empty; failures/deletions isolated, no invented stock.",
            procedure = "Run missing registry/class and failure fixtures.",
            logEvidence = "Coverage capabilities, removal and getter errors.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "BALE-012", group = "BALE", evidence = "fixture",
            description = "Shape sampling limits and detached diagnostics",
            oracle = "Diagnostic samples are capped; native objects/metatables do not escape or execute during serialization.",
            procedure = "Run capped-shape/detachment fixtures.",
            logEvidence = "Explicit sampling/truncation and fixture output.",
            relatedTests = "tests/test_stored_objects.lua, tests/test_inventory.lua"},
        {id = "ANI-001", group = "ANI", evidence = "manual",
            description = "Owned husbandry groups and current counts",
            oracle = "Owned registered husbandries/groups match animal screen; every distinct group counted once.",
            procedure = "Compare animal screen on established save; optionally lbExpect animalsCount value.",
            logEvidence = "Husbandry owner/group count trace and expectation.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-002", group = "ANI", evidence = "manual",
            description = "Native per-animal quote multiplied once",
            oracle = "Reference total equals native unit quote times verified group count; no extra fee/transport deduction.",
            procedure = "Compare group/count and native quote screen, recording UI fees separately.",
            logEvidence = "Unit quote, count, valueSource and total.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-003", group = "ANI", evidence = "manual",
            description = "Zero health/count/quote and empty barn",
            oracle = "Valid zero stays zero; supported empty barn differs from unavailable enumeration.",
            procedure = "Inspect empty supported barn and naturally occurring zero values; fixture unavailable zeros.",
            logEvidence = "Health/count/quote statuses and coverage.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-004", group = "ANI", evidence = "fixture",
            description = "Invalid or missing count and getter precedence",
            oracle = "Fractional/negative/nonfinite count unknown; raw numAnimals used only when getter absent, never to hide a failed getter.",
            procedure = "Run count/getter precedence fixtures.",
            logEvidence = "Getter/field capability and count issue.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-005", group = "ANI", evidence = "fixture",
            description = "Missing quote versus known quantity",
            oracle = "Known animal counts survive failed quote; no zero valuation is invented.",
            procedure = "Run quote failure and healthy-neighbor fixtures.",
            logEvidence = "Unknown-value count and retained count.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-006", group = "ANI", evidence = "manual",
            description = "Age/reproduction unverified units",
            oracle = "Raw diagnostics stay labeled unverified; no claimed months/percent or fertility projection.",
            procedure = "Compare report and diagnostic raw fields with native animal screen.",
            logEvidence = "ageRaw/reproductionRaw and capability flags.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-007", group = "ANI", evidence = "manual",
            description = "Subtype labels and individual horse names",
            oracle = "Native localized label/name preserved; missing metadata uses generic name, not guessed breed.",
            procedure = "Inspect multiple species/groups and named horse when available.",
            logEvidence = "Subtype key/name source and fallback issue.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-008", group = "ANI", evidence = "manual",
            description = "Transport and riding exclusions",
            oracle = "Loaded/ridden animals explicitly outside husbandry coverage; ridden horse never equipment collateral.",
            procedure = "Load/unload animal or ride/return horse when available.",
            logEvidence = "Animal exclusion flags and equipment exclusion.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-009", group = "ANI", evidence = "fixture",
            description = "Duplicate husbandries/clusters and lookup fallback",
            oracle = "Repeated aliases once; separate groups with same attributes stay separate; fallback source named.",
            procedure = "Run dedup and registered-lookup fixtures.",
            logEvidence = "Duplicate counters and row identities.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-010", group = "ANI", evidence = "fixture",
            description = "Unknown owner, failed cluster enumeration and deletion",
            oracle = "Unknown title/removal yields gaps; unreadable husbandry adds unavailable group, not fabricated empty barn.",
            procedure = "Run ownership/cluster/deletion malformed fixtures.",
            logEvidence = "Group issues and status.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-011", group = "ANI", evidence = "fixture",
            description = "Health/metadata validation and overflow",
            oracle = "Health outside 0..100 unavailable; optional object values sanitized; overflowing values/subtotals unavailable.",
            procedure = "Run invalid-health/metadata/extreme count quote fixtures.",
            logEvidence = "Capabilities, overflow issues and scalar rows.",
            relatedTests = "tests/test_animals.lua"},
        {id = "ANI-012", group = "ANI", evidence = "runtime",
            description = "Animal totals separate and observational behavior",
            oracle = "Reference quotes never enter covered collateral or operating cash; capture performs no animal/finance updates.",
            procedure = "Compare subtotal ingredients and use mutation sentinels in fixture.",
            logEvidence = "Asset/financial invariant output and source traces.",
            relatedTests = "tests/test_animals.lua"},
        {id = "FIN-001", group = "FIN", evidence = "manual",
            description = "Retained current Finance category reconciliation",
            oracle = "Raw amounts/signs/zeros and native labels match observed Finance rows; exact source and slot recorded.",
            procedure = "Compare Finance screen at paused time to named checkpoint.",
            logEvidence = "finance source, category key, raw value and screenshot.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-002", group = "FIN", evidence = "manual",
            description = "Retained history slot semantics stay unverified",
            oracle = "No inferred date/order/retention/padding/completeness from slot index or save age.",
            procedure = "Record native slot keys alongside UI; inspect labels and model input provenance.",
            logEvidence = "Raw slot metadata and verification flags.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-003", group = "FIN", evidence = "fixture",
            description = "Stats candidate precedence and farm ownership",
            oracle = "Select one narrow supported source; no merging conflicting candidates; wrong farm excluded.",
            procedure = "Run mission/farm stats fallback, mismatch and competing-source fixtures.",
            logEvidence = "Candidate selection, owner and fallback trace.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-004", group = "FIN", evidence = "fixture",
            description = "Empty/missing/padded retained buckets",
            oracle = "Empty or zero-padded rows never become complete zero-activity periods.",
            procedure = "Run empty/missing/padding fixtures.",
            logEvidence = "Bucket availability and unverified status.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-005", group = "FIN", evidence = "fixture",
            description = "Alias bucket dedup without merging identical independent rows",
            oracle = "Same object alias once; separate equal-value buckets preserved as distinct raw evidence.",
            procedure = "Run alias and independent-bucket fixtures.",
            logEvidence = "Bucket identity/dedup evidence.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-006", group = "FIN", evidence = "fixture",
            description = "Missing declarations and invalid amounts/keys",
            oracle = "Declared missing values unavailable; nonnumeric/nonfinite amounts and non-scalar keys isolated.",
            procedure = "Run malformed metadata/key/value fixtures.",
            logEvidence = "Row status and bounds/shape issues.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-007", group = "FIN", evidence = "fixture",
            description = "Unknown categories, numeric keys and label failures",
            oracle = "Unknown/case-varied keys remain unclassified; native labels optional; no substring guesses.",
            procedure = "Run category/label/malformed label fixtures.",
            logEvidence = "Raw key, native label and classification source.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-008", group = "FIN", evidence = "fixture",
            description = "Retained scan bounds and plain-data export",
            oracle = "Oversized buckets/keys/rows produce explicit truncation; source objects and mutation methods are not used.",
            procedure = "Run >256 buckets, >512 keys or >8192 records and detached-output fixtures.",
            logEvidence = "Scan-bound issues and included counts.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-009", group = "FIN", evidence = "runtime",
            description = "Live MoneyType exact identity classification",
            oracle = "Recognized native identities map to declared operating/capital/financing/interest policy; no guessed numeric constants.",
            procedure = "Inspect each available native mapping in the matrix category subcases; perform known sale/purchase/interest, leaving unobserved categories unexercised.",
            logEvidence = "MoneyType names/raw type, classification and actual delta.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-010", group = "FIN", evidence = "fixture",
            description = "Unknown/conflicting alias identities",
            oracle = "Unknown or conflicting aliases remain unclassified; equality metamethod cannot spoof identity; same-policy aliases coalesce.",
            procedure = "Run exact identity/alias fixtures.",
            logEvidence = "Classifier reasons and fixture output.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-011", group = "FIN", evidence = "manual",
            description = "Animal and custom finance purpose remains uncertain",
            oracle = "Unverified-purpose/custom categories remain unknown rather than invented operating/capital certainty.",
            procedure = "Buy/sell animal or use known custom transaction if already available.",
            logEvidence = "Raw MoneyType/category and eligibility blocker.",
            relatedTests = "tests/test_finance.lua"},
        {id = "FIN-012", group = "FIN", evidence = "runtime",
            description = "Retained records never become observed events",
            oracle = "Opening/reloading archived rows does not replay activity or authorize complete ledger history.",
            procedure = "Compare event/period counts over unchanged repeated captures.",
            logEvidence = "Finance provenance versus observed ledger provenance.",
            relatedTests = "tests/test_finance.lua"},
        {id = "HIST-001", group = "HIST", evidence = "manual",
            description = "New and established saves start with partial observation",
            oracle = "First installed period is partial on both saves; old native rows do not manufacture earlier history.",
            procedure = "Capture both saves before/after first transactions.",
            logEvidence = "Initial ledger, first-period completeness and model reasons.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-002", group = "HIST", evidence = "manual",
            description = "Gross operating inflow and outflow",
            oracle = "Actual receipts/payments remain separate even if net zero; no nominal-price substitution.",
            procedure = "Sell produce and buy supported consumable; compare actual cash changes.",
            logEvidence = "Before/after cash, category, gross totals and reconciliation.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-003", group = "HIST", evidence = "manual",
            description = "Capital movements and valuation independence",
            oracle = "Equipment/land/building sales and purchases remain capital; quote changes are not revenue.",
            procedure = "Perform affordable buy/sell pair and compare ledger.",
            logEvidence = "Capital inflow/outflow and asset quote snapshots.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-004", group = "HIST", evidence = "manual",
            description = "Borrow/repay nesting and principal classification",
            oracle = "Actual matched cash/debt delta recorded exactly once as financing; repayment not operating expense.",
            procedure = "Borrow and repay identical native increment; compare both gross legs and event count.",
            logEvidence = "Loan wrapper/native calls, cash/debt deltas and totals.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-005", group = "HIST", evidence = "manual",
            description = "Interest expense and refund distinction",
            oracle = "Recognized negative native interest separate; positive/refunded unknown interest never invented negative expense.",
            procedure = "Observe ordinary native charge; refund edge fixture-only if no natural path.",
            logEvidence = "Interest identity/direction and class totals.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-006", group = "HIST", evidence = "fixture",
            description = "Requested amount versus actual transaction result",
            oracle = "Ledger uses actual before/after delta, not requested amount; zero actual movement adds no event.",
            procedure = "Run clamped/no-op/partial native transaction fixtures.",
            logEvidence = "Requested and actual delta fields, event count.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-007", group = "HIST", evidence = "fixture",
            description = "Unexplained cash or debt mutation",
            oracle = "Unmatched changes create explicit material gap and withhold eligibility; no balancing fabricated revenue.",
            procedure = "Use fixture or naturally reproduced mod conflict; do not inject hidden game state.",
            logEvidence = "Reconciliation/debt-gap events and reason codes.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-008", group = "HIST", evidence = "fixture",
            description = "Nested ambiguous and failed native transaction",
            oracle = "Ambiguous nested money stays unknown; native error rethrown; observer recovers and does not double-execute.",
            procedure = "Run nested/error/observer-failure fixtures.",
            logEvidence = "Native-call counts, errors and unclassified totals.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-009", group = "HIST", evidence = "fixture",
            description = "Exact argument/return preservation",
            oracle = "Native methods run once with original arguments and nil-containing return tuple; observer failure cannot swallow result.",
            procedure = "Run wrapper contract fixtures.",
            logEvidence = "Contract fixture assertions and hook trace.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-010", group = "HIST", evidence = "manual",
            description = "Adjacent native period boundary observed promptly",
            oracle = "Completed period closes once; next period qualifies only after timely adjacent boundary; installation partial stays partial.",
            procedure = "Cross natural midnight at 1x near boundary; inspect within first game minute.",
            logEvidence = "Before/after monotonic day, period, dayTime and completeness.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-011", group = "HIST", evidence = "manual",
            description = "Native 12 to 1 local-cycle rollover",
            oracle = "Local cycle increments once; no Gregorian-year inference or duplicate seasonal slot.",
            procedure = "Cross actual native 12-to-1 boundary during extended run.",
            logEvidence = "Cycle/period anchors and closed history.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-012", group = "HIST", evidence = "fixture",
            description = "Skipped/late/backward calendar transition",
            oracle = "Sleep that misses opening, skipped day/period or rollback cannot compress gaps into complete history.",
            procedure = "Use normal sleep for late case; skipped/backward synthetic paths remain fixtures.",
            logEvidence = "Calendar discontinuity/gap and eligibility reasons.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-013", group = "HIST", evidence = "manual",
            description = "Days-per-period settings change",
            oracle = "Changed period length invalidates incomparable history and discloses gap.",
            procedure = "On disposable branch change normal days-per-month setting and wait until effective.",
            logEvidence = "Old/new daysPerPeriod, retained periods and gap.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-014", group = "HIST", evidence = "fixture",
            description = "Per-farm continuity and observer capability loss",
            oracle = "Switch/missing farm/calendar/cash/hooks does not reuse previous farm history or claim ongoing complete observation.",
            procedure = "Run farm/capability-loss fixtures.",
            logEvidence = "Capabilities, active farm and material gaps.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-015", group = "HIST", evidence = "runtime",
            description = "Cash reconciliation and tolerance boundary",
            oracle = "Opening cash plus all gross signed flows matches closing cash within 0.01; unknown flows cannot net away evidence gap.",
            procedure = "Check each captured current/closed record; fixture inside/outside tolerance.",
            logEvidence = "Period arithmetic and unknown-flow checks.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-016", group = "HIST", evidence = "fixture",
            description = "Bounded history/categories/gaps and numeric limits",
            oracle = "At most 36 closed periods; bounded categories/gaps; overflow/invalid delta disclosed without nonfinite state.",
            procedure = "Run >36 periods, category limit and extreme numeric fixtures.",
            logEvidence = "Counts, overflow/gap markers and fixture output.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "HIST-017", group = "HIST", evidence = "fixture",
            description = "Current partial, zero activity and detached report",
            oracle = "Current period never counted complete; idle period is not failed payment; copied report cannot mutate ledger.",
            procedure = "Run current/idle/detached state fixtures.",
            logEvidence = "Period statuses and fixture output.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-001", group = "SAVE", evidence = "manual",
            description = "Native save callback writes current directory",
            oracle = "Sidecar path uses callback-time directory, including tempsavegame, and appears in final savegameN after native success.",
            procedure = "Save normally, wait for completion; inspect log and final sidecar without moving temporary files.",
            logEvidence = "Save callback path/write outcome and final-file evidence.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-002", group = "SAVE", evidence = "manual",
            description = "Clean save/reload preserves exact observed state",
            oracle = "Same farm/cash/debt/calendar resumes once, including mode, gross categories, event counts and closed periods.",
            procedure = "Save, quit, reload without deliberate advancement, compare named checkpoints.",
            logEvidence = "Saved/read anchors, resume decision and equal totals.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-003", group = "SAVE", evidence = "manual",
            description = "Second save cycle and no duplicate observations",
            oracle = "Further transactions saved/reloaded once; repeated save does not duplicate events.",
            procedure = "Transact, save twice, reload and compare counts.",
            logEvidence = "Save sequence, persisted totals and resume checks.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-004", group = "SAVE", evidence = "manual",
            description = "Exit without saving discards unsaved bank events",
            oracle = "Native money and bank ledger return to last saved state; Refresh/exit alone writes no sidecar.",
            procedure = "On disposable save transact then quit without save and reload.",
            logEvidence = "Last save/unsaved checkpoint versus reloaded anchor.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-005", group = "SAVE", evidence = "manual",
            description = "Cross-save/farm isolation in one game process",
            oracle = "Each save/farm reads its own sidecar; no stale policy or ledger leaks.",
            procedure = "Switch test saves without restarting; save/reload each.",
            logEvidence = "Save paths, farm IDs and mission/session IDs.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-006", group = "SAVE", evidence = "manual",
            description = "Missing sidecar",
            oracle = "Missing file starts new partial observation with reason; native save remains playable; normal save recreates file.",
            procedure = "With FS25 closed remove only sidecar on a disposable copy, reload and save.",
            logEvidence = "Missing-file load note and initial partial ledger.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-007", group = "SAVE", evidence = "manual",
            description = "Mod disabled during intervening play",
            oracle = "Changed anchors prevent silently joining discontinuous history; limitation for identical anchors disclosed.",
            procedure = "Disable mod on a copy, change cash/calendar normally, save, re-enable.",
            logEvidence = "Anchor mismatch and restart/gap evidence.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-008", group = "SAVE", evidence = "fixture",
            description = "Restored backup or stale copied sidecar",
            oracle = "Cash/debt/calendar/farm/period-length mismatch rejects continuity; same-anchor hidden edits are not claimed detectable.",
            procedure = "Use fixture mismatches; whole-folder backups for real play.",
            logEvidence = "Mismatch reason with saved/current anchors.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-009", group = "SAVE", evidence = "fixture",
            description = "Exact precision and typed XML round trip",
            oracle = "17-digit numeric strings preserve anchors; no float32 rounding or executable serialization.",
            procedure = "Run typed XML round-trip fixture with fractional large values.",
            logEvidence = "Written/read fields and equality assertions.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-010", group = "SAVE", evidence = "fixture",
            description = "Schema, identity, count and ordering validation",
            oracle = "Unsupported schema, invalid identity/count/order/current period are rejected rather than trusted.",
            procedure = "Run malformed XML/storage fixtures.",
            logEvidence = "Load validation reason and discarded continuity.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-011", group = "SAVE", evidence = "fixture",
            description = "Period amount/category integrity",
            oracle = "Negative/nonfinite amount, duplicate category or invalid class rejected; bad cash reconciliation/gaps cannot manufacture complete evidence.",
            procedure = "Run corrupt period/category fixtures.",
            logEvidence = "Load status and completeness/reconciliation.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-012", group = "SAVE", evidence = "fixture",
            description = "Missing hooks or native XML APIs",
            oracle = "Unavailable persistence stated; no successful-save claim or fabricated fallback file path.",
            procedure = "Run missing save/XML functions and absent directory fixtures.",
            logEvidence = "Persistence capabilities and lastSave failure.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-013", group = "SAVE", evidence = "fixture",
            description = "Native save failure and whole-save completion distinction",
            oracle = "Thrown/false native save does not write success; sidecar written never proves final native save completed.",
            procedure = "Run native save failure fixtures; actual fault only if safely reproducible.",
            logEvidence = "Native result, sidecar result and completion caveat.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-014", group = "SAVE", evidence = "fixture",
            description = "Create/load/write/delete failure and handle cleanup",
            oracle = "Failed/zero handle, false/nil save acknowledgement, exceptions release handles and report failure.",
            procedure = "Run XML failure fixtures without disk-filling or damaging live save.",
            logEvidence = "Write/read errors and handle counts.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-015", group = "SAVE", evidence = "manual",
            description = "Policy save scope and read-only native data",
            oracle = "Policy persists only with normal game save; bank changes only its own sidecar and never native economic fields.",
            procedure = "Change policy, save/reload; unsaved-policy branch optional.",
            logEvidence = "Mode, save trace and native figures.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "SAVE-016", group = "SAVE", evidence = "manual",
            description = "Save-load hook ordering on real FS25 version",
            oracle = "Load hook resumes before clock movement; real callback directory promotion matches assumptions on recorded game build.",
            procedure = "Review clean reload trace and final path for both saves.",
            logEvidence = "Game version, early-load timing, anchors and save paths.",
            relatedTests = "tests/test_history.lua, tests/test_history_runtime.lua"},
        {id = "FORE-001", group = "FORE", evidence = "manual",
            description = "Insufficient history produces no fabricated forecast",
            oracle = "New/old save without 12 qualifying observed periods shows reasons and no invented seasonal rows.",
            procedure = "Inspect initial checkpoints under all policies.",
            logEvidence = "Forecast status/window/reasons.",
            relatedTests = "tests/test_underwriting.lua, tests/test_history_runtime.lua"},
        {id = "FORE-002", group = "FORE", evidence = "fixture",
            description = "Twelve consecutive complete periods and exact window",
            oracle = "Only 12 immediately preceding complete reconciled periods qualify; arbitrary latest rows/gaps/duplicates do not.",
            procedure = "Run short/gap/date/duplicate fixtures.",
            logEvidence = "Accepted/rejected window evidence.",
            relatedTests = "tests/test_underwriting.lua, tests/test_history_runtime.lua"},
        {id = "FORE-003", group = "FORE", evidence = "manual",
            description = "Real engine full seasonal observation",
            oracle = "After initial partial plus 12 complete observed periods, actual native ledger can qualify without injected complete flags.",
            procedure = "Run extended ordinary-time route across at least 13 boundaries.",
            logEvidence = "Boundary/save traces and qualified window.",
            relatedTests = "tests/test_underwriting.lua, tests/test_history_runtime.lua"},
        {id = "FORE-004", group = "FORE", evidence = "manual",
            description = "Matching-season repeat and horizon",
            oracle = "Each next full period repeats matching observed slot; current partial omitted; source slot attached.",
            procedure = "On genuinely eligible save compare 12 forecast rows with observed source rows.",
            logEvidence = "Forecast rows, source cycle/period and annual sums.",
            relatedTests = "tests/test_underwriting.lua, tests/test_history_runtime.lua"},
        {id = "FORE-005", group = "FORE", evidence = "fixture",
            description = "Gross scenario amounts and excluded flows",
            oracle = "Project only operating receipts/payments and interest; capital/financing and asset values do not enter seasonal cash.",
            procedure = "Run distinctive seasonal/category fixture.",
            logEvidence = "Projected components and source mapping.",
            relatedTests = "tests/test_underwriting.lua, tests/test_history_runtime.lua"},
        {id = "FORE-006", group = "FORE", evidence = "fixture",
            description = "Material gaps, malformed inputs and cross-farm data",
            oracle = "Unverified coverage, wrong farm/date, unknown flows or overflow withholds scenario; no confident fallback average.",
            procedure = "Run financial evidence-gate fixtures.",
            logEvidence = "Reason codes and absent numeric scenario.",
            relatedTests = "tests/test_underwriting.lua, tests/test_history_runtime.lua"},
        {id = "FORE-007", group = "FORE", evidence = "fixture",
            description = "Zero activity and limited confidence",
            oracle = "Verified idle cycle may yield zero repeat scenario but no score; shorter data never annualized.",
            procedure = "Run complete-idle/shorter-window fixtures.",
            logEvidence = "Forecast confidence, observed subtotal and assessment.",
            relatedTests = "tests/test_underwriting.lua, tests/test_history_runtime.lua"},
        {id = "FORE-008", group = "FORE", evidence = "manual",
            description = "Forecast wording and omitted obligations",
            oracle = "Conditional single-cycle repeat is labeled; no predicted yield/price, ending balance, profit, safe installment or principal coverage.",
            procedure = "Inspect forecast on eligible fixture and real eligible save when achieved.",
            logEvidence = "Assumptions/caveats in report and snapshot.",
            relatedTests = "tests/test_underwriting.lua, tests/test_history_runtime.lua"},
        {id = "SCORE-001", group = "SCORE", evidence = "manual",
            description = "No score before evidence gates pass",
            oracle = "New, established-only, partial or unavailable data yields no numeric score/band under every policy.",
            procedure = "Inspect initial saves and policy cycle.",
            logEvidence = "Assessment status, absent score/band and reasons.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-002", group = "SCORE", evidence = "fixture",
            description = "Complete classified reconciled matching-farm evidence",
            oracle = "12 consecutive complete periods, all gross categories, verified current cash/debt and clear material coverage required.",
            procedure = "Run missing/category/date/farm/gap gate fixtures.",
            logEvidence = "Eligibility reasons and accepted period count.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-003", group = "SCORE", evidence = "fixture",
            description = "Unknown gross inflows/outflows do not cancel",
            oracle = "Equal unknown inflow/outflow still blocks assessment.",
            procedure = "Run offsetting-unclassified fixture.",
            logEvidence = "Both gross unknown amounts and blocker.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-004", group = "SCORE", evidence = "fixture",
            description = "Debt with no observed interest and idle year",
            oracle = "Positive debt without interest evidence or inactive operating year withholds score; neither gets invented failed grade.",
            procedure = "Run debt-no-interest and idle fixtures.",
            logEvidence = "Evidence reasons and absent score.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-005", group = "SCORE", evidence = "fixture",
            description = "Margin component arithmetic",
            oracle = "35-point operating margin uses operating cash before interest divided by receipts, bounded by mode thresholds.",
            procedure = "Recalculate independent fixture cases at/inside/outside thresholds.",
            logEvidence = "Component raw value, thresholds, weight and points.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-006", group = "SCORE", evidence = "fixture",
            description = "Cash-buffer component arithmetic",
            oracle = "30-point buffer uses current cash divided by mean monthly operating expense plus interest.",
            procedure = "Check negative cash, ordinary costs and verified no-cost special case.",
            logEvidence = "Buffer formula/value/special-case/points.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-007", group = "SCORE", evidence = "fixture",
            description = "Native-interest component arithmetic",
            oracle = "20-point interest coverage uses operating cash before interest over native interest; zero-burden case explicit.",
            procedure = "Check losses, positive/zero interest and debt evidence boundary.",
            logEvidence = "Interest formula/value/reasons/points.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-008", group = "SCORE", evidence = "fixture",
            description = "Native-debt component arithmetic",
            oracle = "15-point leverage uses debt over positive operating cash; no debt full points; nonpositive cash flow no infinity.",
            procedure = "Check zero/positive debt and nonpositive operating cash cases.",
            logEvidence = "Debt ratio or special status, thresholds and points.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-009", group = "SCORE", evidence = "fixture",
            description = "Score rounding, clamping and bands",
            oracle = "Finite rounded total stays 0..100; >=75 favorable, >=50 guarded, otherwise strained.",
            procedure = "Recalculate boundary cases including 49/50/74/75 and saturation.",
            logEvidence = "Component sum, final score and band.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-010", group = "SCORE", evidence = "fixture",
            description = "Mode monotonicity and immutable policy thresholds",
            oracle = "Same valid evidence yields Lenient >= Standard >= Strict; returned policy mutation cannot alter future result.",
            procedure = "Run mode ordering and copied-policy fixtures.",
            logEvidence = "Mode thresholds and score comparisons.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-011", group = "SCORE", evidence = "manual",
            description = "Real eligible policy control and persistence",
            oracle = "Eligible real ledger displays transparent components; cycling mode changes thresholds only; saved mode resumes.",
            procedure = "After real seasonal qualification, cycle controls and save/reload.",
            logEvidence = "Mode/source snapshots and saved/read mode.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-012", group = "SCORE", evidence = "fixture",
            description = "Capital, financing and collateral independence",
            oracle = "Borrowing/capital sales/asset appreciation cannot create operating earnings or direct score points; cash/debt effects remain real.",
            procedure = "Run model isolation fixture with controlled evidence.",
            logEvidence = "Operating measures, collateral and component inputs.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-013", group = "SCORE", evidence = "fixture",
            description = "External-liability scope and provisional label",
            oracle = "Unverified external liabilities make score provisional; suspected material unknown liability withholds score.",
            procedure = "Run options fixture and inspect live native-only default.",
            logEvidence = "Scope flags, provisional status and reasons.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-014", group = "SCORE", evidence = "fixture",
            description = "Negative cash/loss, invalid values and arithmetic overflow",
            oracle = "Adverse known figures get explicit reasons; missing/nonfinite/overflow cannot become arbitrary bounded score.",
            procedure = "Run loss/cash/overflow fixtures.",
            logEvidence = "Reason codes and unavailable outputs.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-015", group = "SCORE", evidence = "manual",
            description = "No invented underwriting facts or approval",
            oracle = "Score is transparent internal simulation; no bureau/default probability, payment history, accounting profit, DSCR or lending approval claim.",
            procedure = "Inspect full assessment and explanations.",
            logEvidence = "Model version, scope and unavailable obligations.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "SCORE-016", group = "SCORE", evidence = "runtime",
            description = "Partial collateral calculation and no stale figures",
            oracle = "Known land/equipment/building quotes separate; inventory/animal/cash duplication excluded; unavailable stale values ignored.",
            procedure = "Compare subtotal/debt ratio to supported values and run stale-value fixture.",
            logEvidence = "Collateral inputs/status and invariants.",
            relatedTests = "tests/test_underwriting.lua"},
        {id = "DEBUG-001", group = "DEBUG", evidence = "manual",
            description = "Validation-release startup configuration",
            oracle = "0.0.6 begins enabled with read tracing; config false or lbDebug off stops diagnostic work without disabling bank.",
            procedure = "Launch defaults, disable/re-enable, reload with config false on disposable install if needed.",
            logEvidence = "Configuration/mode transitions and quiet period.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-002", group = "DEBUG", evidence = "manual",
            description = "Diagnostic commands and invalid input",
            oracle = "lbDebug on/trace/off/summary, lbValidate label and lbMark label respond without crashing; malformed args are rejected/useful.",
            procedure = "Run each command and invalid mode/empty label variants.",
            logEvidence = "Command responses and labeled checkpoints.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-003", group = "DEBUG", evidence = "runtime",
            description = "Automatic capture reasons and bounded frequency",
            oracle = "First-ready/open/Refresh/save/reload/settled transaction/boundary captures are attributable and coalesced, not per-frame full scans.",
            procedure = "Follow short route and inspect capture reason/count over idle interval.",
            logEvidence = "Capture sequence/reasons/timing and limits.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-004", group = "DEBUG", evidence = "runtime",
            description = "Read provenance, classification and exclusion evidence",
            oracle = "Trace identifies attempted accessor/field, type/status, fallback and include/exclude reason without extra economic reads.",
            procedure = "Inspect representative successful, missing and excluded source traces; use fixtures for faults.",
            logEvidence = "Read and decision events with source and reason.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-005", group = "DEBUG", evidence = "runtime",
            description = "Full snapshot schema and explicit truncation",
            oracle = "Bounded checkpoint serialization includes available values/statuses; exceeding limits emits explicit truncation, never silently claims completeness.",
            procedure = "Inspect ordinary checkpoint and oversized local fixture.",
            logEvidence = "Snapshot records, budgets, truncation markers.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-006", group = "DEBUG", evidence = "manual",
            description = "Manual expectation comparisons",
            oracle = "lbExpect cash/debt/landCount/equipmentOwned/animalsCount records independently read UI value and compares it; user entry is not proof UI correct.",
            procedure = "Enter one correct native value and one deliberately wrong expectation, then enter the correct value again; retain each checkpoint result.",
            logEvidence = "Metric, expected/actual, provenance and result.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-007", group = "DEBUG", evidence = "runtime",
            description = "Scenario catalog completeness accounting",
            oracle = "Every catalog ID remains visible with NOT_EXERCISED until warranted evidence; absent asset/path is not automatic PASS.",
            procedure = "Generate summary for empty and populated saves and review missing groups.",
            logEvidence = "Catalog IDs, statuses and coverage counts.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-008", group = "DEBUG", evidence = "manual",
            description = "Internal invariant PASS versus native accuracy",
            oracle = "Arithmetic/source agreement checks never certify unseen game UI, assets, long periods or arbitrary mod compatibility.",
            procedure = "Review analyzer output against manual matrix evidence.",
            logEvidence = "Result scope/provenance and unexercised list.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-009", group = "DEBUG", evidence = "fixture",
            description = "Failure visibility and diagnostic self-protection",
            oracle = "Collector/serializer/check exception produces diagnostic failure or unavailable, never swallows native transaction or crashes bank.",
            procedure = "Run failing serializer/sink/check fixture where implemented.",
            logEvidence = "Diagnostic errors, native-call preservation and fixture result.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-010", group = "DEBUG", evidence = "fixture",
            description = "Bounded logs, scalar sanitization and stable IDs",
            oracle = "Oversized strings/tables/cycles/metatables stay bounded/sanitized; no retained live refs; order/IDs stable enough to compare.",
            procedure = "Run oversized/cyclic/malformed diagnostic fixtures.",
            logEvidence = "Budget/cycle markers and deterministic records.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-011", group = "DEBUG", evidence = "runtime",
            description = "Summary counts and non-exercised branches",
            oracle = "Summary separates PASS/FAIL/WARN/UNAVAILABLE/NOT_EXERCISED; missing/partial logs cannot collapse into all-pass.",
            procedure = "Compare summary to emitted check results and intentional mismatch.",
            logEvidence = "Summary counts, coverage and detected failures.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-012", group = "DEBUG", evidence = "manual",
            description = "Offline analyzer parses real log and preserves evidence",
            oracle = "Analyzer extracts bank events amid unrelated log lines and emits Markdown/optional JSON with precise findings and checkpoint links.",
            procedure = "Run tools/analyze_log.py on saved complete Windows log.",
            logEvidence = "Analyzer command/output and original log.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-013", group = "DEBUG", evidence = "fixture",
            description = "Analyzer malformed/truncated/repeated-session inputs",
            oracle = "Bad lines/truncation/duplicate events/session changes are reported or handled without invented evidence; unknown IDs retained.",
            procedure = "Run analyzer fixtures or documented synthetic logs; keep them distinct from Windows evidence.",
            logEvidence = "Parser warnings and session/checkpoint attribution.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-014", group = "DEBUG", evidence = "fixture",
            description = "Diagnostics off/on economy and result equivalence",
            oracle = "Enabling trace does not call collectors/getters twice, change classification/score, or duplicate transactions/save hooks.",
            procedure = "Compare identical scripted sequence with diagnostics enabled and disabled.",
            logEvidence = "Call counts, snapshots and event deltas.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-015", group = "DEBUG", evidence = "manual",
            description = "Unload/reload diagnostics lifecycle and command cleanup",
            oracle = "New mission/session identity starts clean; no callbacks or old expectations/checkpoints attach to wrong save.",
            procedure = "Use second-save route and compare trace/command registration.",
            logEvidence = "Teardown, command lifecycle and session IDs.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-016", group = "DEBUG", evidence = "manual",
            description = "Log collection provenance and reproducibility",
            oracle = "Evidence records ZIP hash, game version, map/mods, settings, save identity and actions; original log retained before next launch.",
            procedure = "Save log and analyzer output with route notes/screenshots.",
            logEvidence = "Evidence bundle metadata and original timestamps.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
        {id = "DEBUG-017", group = "DEBUG", evidence = "fixture",
            description = "Automatic pure-Lua model and ledger probes",
            oracle = "Run once on detached synthetic input without changing native time, money or history; origin=synthetic and SYNTHETIC_* IDs stay separate from runtime coverage.",
            procedure = "Inspect startup probe results and source isolation; confirm synthetic twelve-period success cannot pass real seasonal qualification.",
            logEvidence = "Synthetic origin/check IDs, probe result and separate runtime/scenario summaries.",
            relatedTests = "diagnostic/analyzer tests; see tests/run.lua"},
    }
}

return BankValidationCatalog
